---

- name: hourly content
  copy:
    content: "{{item.content}}"
    dest: "/etc/cron.hourly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_hourly}}"
  when: item.content is defined

- name: hourly template
  template:
    src: "{{item.template}}"
    dest: "/etc/cron.hourly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_hourly}}"
  when: item.template is defined

- name: daily content
  copy:
    content: "{{item.content}}"
    dest: "/etc/cron.daily/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_daily}}"
  when: item.content is defined

- name: daily template
  template:
    src: "{{item.template}}"
    dest: "/etc/cron.daily/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_daily}}"
  when: item.template is defined

- name: weekly content
  copy:
    content: "{{item.content}}"
    dest: "/etc/cron.weekly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_weekly}}"
  when: item.content is defined

- name: weekly template
  template:
    content: "{{item.template}}"
    dest: "/etc/cron.weekly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_weekly}}"
  when: item.template is defined

- name: monthly content
  copy:
    content: "{{item.content}}"
    dest: "/etc/cron.monthly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_monthly}}"
  when: item.content is defined

- name: monthly template
  template:
    content: "{{item.template}}"
    dest: "/etc/cron.monthly/{{item.filename}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default(0755)}}"
  with_items: "{{cron_monthly}}"
  when: item.template is defined

- name: cron.d
  template:
    src=crond.j2
    dest=/etc/cron.d/{{item.filename}}
    owner="{{item.owner|default('root')}}"
    group="{{item.group|default('root')}}"
    mode="{{item.mode|default(0644)}}"
  with_items: "{{cron_d}}"

